version: '3'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "${DOCKER_HOST_POSTGRES_PORT:-5440}:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bench

  migrate:
    container_name: migrate-local
    image: migrate/migrate:v4.15.1
    restart: "no"
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "migrate", "--path=/migrations", "--database=postgres://user:password@postgres:5432/bench?sslmode=disable" ]
    command: [ "up" ]

  mongo:
    image: bitnami/mongodb:5.0.18
    ports:
      - "${DOCKER_HOST_MONGO_PORT:-27017}:27017"
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_DATABASE: bench
